version: '3.3'

services:
  web:
    build:
      context: ../web/
      args:
        - NODE_ENV=development
    container_name: nextJS
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:  
      - ../web:/web
      - /web/node_modules
      - /web/.next

  node-red:
    image: nodered/node-red:latest
    container_name: nodered
    environment:
      - TZ=Europe/Madrid
    ports:
      - '1880:1880'
    volumes:
      - ../data/nodered:/data
      - ../system:/tmp

  webserver:
    container_name: "webserverNextJS"
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - 'web'
      - 'node-red'
    volumes:
      - ./nginx:/etc/nginx/conf.d
